# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NextWhere' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 4.4'
	pod "youtube-ios-player-helper", "~> 0.1.4"
	pod 'AKMaskField'
	pod 'FBSDKCoreKit'
	pod 'FBSDKShareKit'
  # Pods for NextWhere

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
end
